plugins {
    id 'java'
}

group = 'abyss'
version = '1.0.0'

sourceCompatibility = 1.8
targetCompatibility = 1.8

repositories {
    mavenCentral()
    maven {
        name = 'MinecraftForge'
        url = 'https://maven.minecraftforge.net/'
    }
    maven {
        name = 'SpongePowered'
        url = 'https://repo.spongepowered.org/maven/'
    }
    maven {
        name = 'Mojang'
        url = 'https://libraries.minecraft.net/'
    }
}

dependencies {
    // Compile-time references against local Minecraft Forge libraries if present
    compileOnly fileTree(dir: 'E:/minecraft/libraries', include: ['**/*.jar'])
    compileOnly fileTree(dir: 'E:/minecraft/versions/1.8.9', include: ['**/*.jar'])
    
    // Core dependencies
    compileOnly 'net.minecraft:launchwrapper:1.12'
    compileOnly 'org.ow2.asm:asm-all:5.0.3'
    compileOnly 'com.google.code.gson:gson:2.2.4'
    compileOnly 'com.google.guava:guava:17.0'
    compileOnly 'org.lwjgl.lwjgl:lwjgl:2.9.4-nightly-20150209'
    compileOnly 'org.lwjgl.lwjgl:lwjgl_util:2.9.4-nightly-20150209'
    compileOnly 'io.netty:netty-all:4.0.23.Final'
    compileOnly 'org.apache.logging.log4j:log4j-api:2.0-beta9'
    compileOnly 'org.apache.logging.log4j:log4j-core:2.0-beta9'
    compileOnly 'commons-io:commons-io:2.4'
    compileOnly 'org.apache.commons:commons-lang3:3.3.2'
    compileOnly 'net.sf.jopt-simple:jopt-simple:4.6'
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
    options.compilerArgs += ['-XDignore.symbol.file']
}

jar {
    manifest {
        attributes(
            'Manifest-Version': '1.0',
            'Main-Class': 'net.minecraft.launchwrapper.Launch',
            'FMLCorePlugin': 'Abyss.ASM.CoreMod',
            'FMLCorePluginContainsFMLMod': 'true',
            'ModSide': 'CLIENT',
            'ForceLoadAsMod': 'true'
        )
    }
}
